### ISSUE TITLE
15.8.2 WebKit now also has broken elements

### ISSUE THREAD

**Issue by Egaliterrier** [PoomSmart/GitHubWebLegacyCompat#6]
As shown below, browsers on my device (running iOS 15.8.2) can no longer load certain elements on GitHub. Specifically things like the commit date for folders/files and issue comments/updates - seems to affect elements that aren't initially loaded before the main page load is done or until they are in view. I could very well be off about that being significant (or even correct).
I’m guessing the same is true for all WebKit versions included with 15.4-15.8.4. 
Have tried with and without messing with experimental Safari settings, making sure to clean the relevant caches between troubleshooting attempts etc. to be safe - issue persists regardless of settings and browser.

![Image](https://github.com/user-attachments/assets/fee46c19-83df-40ce-94fd-37a1ec6611e2)

![Image](https://github.com/user-attachments/assets/ccd4ceff-85da-43bc-b987-387586056645)

**Comment by gorloffslava** [comment]
The same happens on iOS 16. In particular, on iPadOS 16.2.
I'm getting the following error in console twice:
`SyntaxError Duplicate parameter `e` in function with destructuring with assignment`

Seems it was a bug inside WebKit fixed during iOS 17 days: 
1. https://bugs.webkit.org/show_bug.cgi?id=220517
2. https://bugs.webkit.org/show_bug.cgi?id=247433

**Comment by Egaliterrier** [comment]
> The same happens on iOS 16. In particular, on iPadOS 16.2. I'm getting the following error in console twice: `SyntaxError Duplicate parameter `e` in function with destructuring with assignment`
> 
> Seems it was a bug inside WebKit fixed during iOS 17 days:
> 
>     1. https://bugs.webkit.org/show_bug.cgi?id=220517
> 
>     2. https://bugs.webkit.org/show_bug.cgi?id=247433

Did it start happening within the last week for you too? Because this issue started for me out of nowhere the day I posted this, and nothing in githubs changelog or roadmap mentions any changes that could plausibly cause it, which is probably typical of such a change these days.

**Comment by gorloffslava** [comment]
@Egaliterrier This happened to me exactly on the day you've posted your issue, yes. 
Looks like it caused by ReactJS code minification (as the original bug fixed in WebKit).

**Comment by PoomSmart** [comment]
I'd want to see if GitHub would be willing to fix this issue themselves first.

**Comment by PoomSmart** [comment]
Yep, they fixed it.

**Comment by Egaliterrier** [comment]
Fantastic. In any case, thanks for your work in keeping legacy iOS jailbreaks alive Poomsmart.

**Comment by jefferyto** [comment]
I have devices on iOS 15.4 (iPhone SE 2022) and 15.8.4 (iPhone 7 Plus), and GitHub is still broken in the ways described in the first post.

**Comment by Egaliterrier** [comment]
Yeah, it's been this way for a week or two now. Figured I'd wait and see if GitHub fixes it on their side once again, but it feels more and more likely that it's permanent this time.
